## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
# q1 Creating DataFrame
frame = pd.DataFrame(data)
print("DataFrame:")
print(frame, "\n")
# q2 People who are psychologist or teacher AND num of cars > fam size
print("q2 Selected people:")
print(frame[((frame["job"] == "psychologist") | (frame["job"] == "teacher")) 
        & (frame["num_cars"] > frame["family_size"])], "\n")
# q3 People who have <= 2 fam size and >= 1 car
print("q3 Selected people:")
print(frame[(frame["family_size"] <= 2) & (frame["num_cars"] >= 1)], "\n")
# q4 Number of unique jobs
print("Number of unique jobs:")
print(len(frame["job"].unique()))

DataFrame:
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1 

q2 Selected people:
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4 

q3 Selected people:
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1 

Number of unique jobs:
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
# Create a dataframe
data = {'fruit':fruit, 'weights': weights}
fruit_df = pd.DataFrame(data)
# Calculate the mean of each fruit
print(fruit_df.groupby('fruit').mean())

        weights
fruit          
apple      5.00
banana     6.25
carrot     5.00


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
# q1
course_sorted = np.argsort(course_name)
print(course_sorted)
# q2
print(np.char.startswith(course_name, 'P'))

[1 3 0 2 4]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
# q1
print('Original:', student_id)
print('Reversed:', student_id[::-1])
# q2
id_sort = np.sort(student_id)[::-1]
print('Three largest values', id_sort[0:3])


Original: [1023 5202 6230 1671 1682 5241 4532]
Reversed: [4532 5241 1682 1671 6230 5202 1023]
Three largest values [6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
# Hint: you can use arange to start off
array = np.arange(0, 100)
print(np.sum((array[(array % 3 == 0) | (array % 5 == 0)])))


2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
# q1
arr[:, [1,2]] = arr[:, [2,1]]
print("q1 \n", arr)

# Assue q2 is swaping the original array
myarr = np.arange(12).reshape(3,4)
# q2
myarr[[0,1], :] = myarr[[1,0], :]
print("q2 \n", myarr)


q1 
 [[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
q2 
 [[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
